fix: avoid panic on notifications access
Sometimes an index out of bounds error would occur due to attempting to
access a notification at an index where there is no notification. The
cause it not currently known (which is why additional error output has
been made), but guarding against the behaviour will at least ensure the
application doesn't end up with a poisoned lock, preventing Rofi from
opening again.

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 8 but the index is 8', src/rofi.rs:63:33
```